rules:
  color-no-invalid-hex: true
  function-calc-no-invalid: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  string-no-newline: true
  unit-no-unknown: true
  keyframe-declaration-no-important: true
  block-no-empty: true
  selector-pseudo-class-no-unknown: true
